### ISSUE TITLE
Create Emote is broken

### ISSUE THREAD

**Issue by hyblocker** [yellowsink/cc-plugins#1]
Create emote is broken, see attached
![image](https://user-images.githubusercontent.com/7695629/140175647-f16ade4a-e375-4b29-952f-c708ab9ffcf3.png)

Canary 103454 (0c58212); powerCord latest

**Comment by yellowsink** [comment]
ah crap okay. tbf i knew this plugin was slightly brokey atm

**Comment by yellowsink** [comment]
do you have the manage emote perm in any servers? cause thats gon be the difference between trivial fix and horrid nightmare

**Comment by hyblocker** [comment]
Of course I do. powerCord's built-in emote utility also broke recently, so I suspect discord changed the way polling permissions works.

**Comment by yellowsink** [comment]
ah shit. that means some command palette entries borked too

**Comment by yellowsink** [comment]
fixed in #2
