### ISSUE TITLE
[Show Username] Add setting to fully replace the nickname with the username

### ISSUE THREAD

**Issue by Delphox** [yellowsink/cc-plugins#15]
Add a setting that instead of appending the username to the nickname to parenthesis, just have the username show instead of nickname. Similar to one of the options from [RemoveNicknames](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/RemoveNicknames) from BD.

![image](https://camo.githubusercontent.com/cc29eed9427ee1bc181fcdc99c984a2ad054bbf4a20ac7e9b9bede6914dcc995/68747470733a2f2f6d776974747269656e2e6769746875622e696f2f426574746572446973636f72644164646f6e732f506c7567696e732f52656d6f76654e69636b6e616d65732f5f7265732f636f7665722e706e67)

**Comment by yellowsink** [comment]
This is a good idea!

**Comment by yellowsink** [comment]
added in 7609c77
